### ISSUE TITLE
command-line usage?

### ISSUE THREAD

**Issue by hoijui** [apertus-open-source-cinema/elmyra#42]
hello! :-)
We would be interested in a command-line create-able approach, as in, a fully automated way of creating renders. It could be used for example, when one has a github repo with OpenSCAD or FreeCAD files, and wants to auto generate renders with CI/CD on each commit.
Does it at all make sense to use/change Elmyra for that, or would one better use Blender directly instead?

**Comment by simonrepp** [comment]
hey there! :wave: 

Given the more linear workflow that is implied I'd venture that maybe just directly scripting Blender (much as elmyra is doing it, just without the stateful interaction) *might* be the more approriate route - in that case you can however still have a look at elmyra's setup (particularly starting at `blender_generate.py` and `blender_renderer.py` and following down the cascade of modules used - `common.py`, `media.py`, `style.py`, etc. - it's really a very simple process you could replicate or reuse)

As for command-line usage of elmyra itself there is at the moment no such feature, but I'm currently in the process of rewriting the server portion of elmyra back into a pure "background process" executable (rust-based) which will make elmyra conveniently server-hostable again - currently it's more of a desktop demo of what it's really supposed to be and I'm going to drop these (js/electron-based) parts as it really defeats the whole concept. And to get to the point, with that rewrite done (and it's not that dramatic of a rewrite really, just a few simple endpoints and some changes to the packaging process) it should be quite trivial to add command line flags to the thing that trigger a one-shot scene generation or a one-shot render process instead of continuous background operation.

So there's some possibilites! :) Happy to see what you come up with - I'd like to mention that you should feel absolutely free to fork elmyra and turn it into something dedicatedly different as well, and if you're curious about the rewrite process, I'm currently pushing into the `blender-2.8` branch where changes accumulate in a monolithic mega WIP commit until stable functionality is restored again. :)

If I can help in any way just let me know, cheers!

**Comment by hoijui** [comment]
WOW, great!! :D
I love rust (still newb though).
.. uff.. thanks a lot for all that.. perfect info!
For me, this is rather a.. quite low priority side-project at the moment, so I am happy to wait till your rewrite is done and use it with little changes or extract from it what we need then.

you have a very important project for the betterment of open hardware documentation there! :-)
great!

**Comment by simonrepp** [comment]
Cool got it, and thanks for the feedback, appreciate it!

**Comment by hoijui** [comment]
:-)

**Comment by simonrepp** [comment]
I've implemented all the changes, elmyra is now up for further customization and hacking again if you wish to do so! Thanks again for your interest! :+1:
