### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by davidak** [apertus-open-source-cinema/elmyra#9]
First i thought i should have Blender installed, but after having it, i still get this error.

It seams you have Blender bundled but it is not working. One sentence to make this more clear in the README would be helpful, like "Blender is bundled and don't have to be installed."

i tried with: https://www.thingiverse.com/download:1223854

```
Blender quit
found bundled python: lib/osx/blender-2.76.0-git20160201.ddc9c76-x86_64/blender.app/Contents/MacOS/../Resources/2.76/python
Traceback (most recent call last):
  File "/Users/davidak/Downloads/osx/renderer-blender.py", line 15, in <module>
    import render
  File "/Users/davidak/Downloads/osx/render.py", line 7, in <module>
    from PIL import Image
  File "/Users/davidak/Downloads/osx/lib/osx/blender-2.76.0-git20160201.ddc9c76-x86_64/blender.app/Contents/Resources/2.76/python/lib/python3.5/site-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: dlopen(/Users/davidak/Downloads/osx/lib/osx/blender-2.76.0-git20160201.ddc9c76-x86_64/blender.app/Contents/Resources/2.76/python/lib/python3.5/site-packages/PIL/_imaging.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/.dylibs/libjpeg.9.dylib
  Referenced from: /Users/davidak/Downloads/osx/lib/osx/blender-2.76.0-git20160201.ddc9c76-x86_64/blender.app/Contents/Resources/2.76/python/lib/python3.5/site-packages/PIL/_imaging.cpython-35m-darwin.so
  Reason: image not found
```

**Comment by simonrepp** [comment]
Uh that's an important discovery actually - seems very much that pillow/PIL relies on dynamic libraries which might or might not be present on some systems and in that way it undermines the whole bundling-everything idea ...

I'll probably have to substitute pillow and do the image blending I'm using it for with ffmpeg or right in blender compositing. Not a show-stopper, but this won't be a quick fix either.

If you want to go on in the meanwhile you can try to `pip3 install pillow`, which might point you to missing system libraries that you can then install on your own and afterwards (given `pip3 install pillow` succeeds) the bundled pillow might find them as well and it could thus work then. I can't promise it though - but I'll see that I have it fixed in the next days anyway. ;)

Once again, a big thank you for the report, this is super helpful.

And I will add a note about the blender bundling, I need to point out that we are still in some unofficial alpha state as well anyway ... oops.

**Comment by davidak** [comment]
pillow get installed without problems, same error running renderer.py

Python 3.5.1 was installed with homebrew on OS X 10.9.5, maybe that helps.

**Comment by simonrepp** [comment]
Well, it was worth a shot, thanks for the feedback :)

In any case, I wouldn't spend any more time on fixing this with pillow (unless you absolutely want to), I'll very likely have a patch for this ready on monday, and then pillow is gone as a dependency anyway ... And then any further time spent on this is actually lost time. :)

**Comment by davidak** [comment]
it is not important at all for me that this is fixed now. i just wanted to help the development with testing how the current state works.

**Comment by simonrepp** [comment]
and you did! :) :+1:

**Comment by simonrepp** [comment]
Pillow is out, replaced the image-stacking code with an ffmpeg-based implementation d99b21d62ef836be819dc68427f10e36f4c43993 New releases are up in the next 10 minutes.

Let me know if there's an issue with the patch. :)

**Comment by davidak** [comment]
problem solved :+1:
